language: python
sudo: false

python:
  - "3.6"
# command to install dependencies

branches:
  only:
    - master
    - dev

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

# command to run tests
script:
  - python test_app.py
